/**
 * <gorilla-sim> — count the passes, once.
 *
 * The design is spent after one viewing per subject, which is the whole reason
 * the original needed a large sample: you cannot un-know it. So the panel does
 * the same thing. There are two beats behind two tabs:
 *
 *   The trial   — one honest run at the counting task. The gorilla walks
 *                 through in plain view. The count is asked for first and only
 *                 then the other question, and the gorilla is never revealed
 *                 before the count is in.
 *   The insight — the metacognitive point: attention gates awareness, the miss
 *                 is invisible from the inside, and load decides who misses it.
 *                 It stays LOCKED until the trial is spent, so nobody reads why
 *                 they missed it before they have had their one naive viewing.
 *
 * The counting task is real. Passes are generated by the ball actually being
 * thrown between players and the tally is whatever happened, so a reader who
 * concentrates gets it about right, which is what makes the miss worth
 * anything. Watching a second time is a different experiment, and the panel
 * says so — on any replay the gorilla is ringed and never pretends to be naive.
 */

import { SimElement, clamp, defineSim, noise, prefersReducedMotion } from './base';

type Mode = 'trial' | 'insight';
type Phase = 'idle' | 'playing' | 'counting' | 'asked' | 'done';

interface Player {
  x: number;
  y: number;
  vx: number;
  vy: number;
  light: boolean;
}

const W = 320;
const H = 200;
const PAD = 22;
const DURATION_MS = 16000;
const TICK_MS = 40;
const PASS_MS = 700;
/** When the gorilla walks through, as a fraction of the whole clip. */
const GORILLA_FROM = 0.5;
const GORILLA_TO = 0.72;

class GorillaSim extends SimElement {
  private mode: Mode = 'trial';
  private phase: Phase = 'idle';
  private t = 0;
  private timer = 0;
  private players: Player[] = [];
  private from = 0;
  private to = 1;
  private passStart = 0;
  private passes = 0;
  private guess: number | null = null;
  private sawIt: boolean | null = null;
  private viewings = 0;
  /** After the first run, the gorilla is drawn ringed. */
  private marked = false;
  /** True once the reader has finished one trial — unlocks the insight tab. */
  private revealed = false;
  /** True when the one viewing that revealed it never actually animated. */
  private silent = false;

  protected setup(): void {
    // The start/reset buttons are rebuilt per phase, so they carry their own
    // listeners; only the fixed controls are wired here.
    this.onClick('[data-sim-mode]', el => this.setMode(el.dataset.simMode as Mode));
    this.onClick('[data-sim-submit]', () => this.submitCount());
    this.onClick('[data-sim-saw]', el => this.answerSaw(el.dataset.simSaw === 'yes'));
    this.on('[data-sim-count]', 'keydown', (_el, event) => {
      if ((event as KeyboardEvent).key === 'Enter') {
        event.preventDefault();
        this.submitCount();
      }
    });
    this.buildControls();
  }

  protected teardown(): void {
    if (this.timer) this.cancelInterval(this.timer);
  }

  /* ── tabs ── */

  private setMode(mode: Mode): void {
    // The insight is locked until the trial is spent. Refuse to switch to it
    // early, even if something clicks the disabled tab.
    if (mode === 'insight' && !this.revealed) return;
    if (mode === this.mode) return;
    this.mode = mode;
    this.buildControls();
    this.render();
    this.emit(`mode-${mode}`);
  }

  /* ── the clip ── */

  private start(): void {
    this.viewings += 1;
    this.marked = this.viewings > 1;
    this.silent = false;
    this.phase = 'playing';
    this.t = 0;
    this.passes = 0;
    this.guess = null;
    this.sawIt = null;
    this.passStart = 0;

    this.players = Array.from({ length: 6 }, (_, i) => ({
      x: PAD + noise(i * 37 + this.viewings * 13) * (W - 2 * PAD),
      y: PAD + noise(i * 91 + this.viewings * 7) * (H - 2 * PAD),
      vx: (noise(i * 17 + 3) - 0.5) * 2.6,
      vy: (noise(i * 53 + 5) - 0.5) * 2.6,
      light: i < 3,
    }));
    this.from = 0;
    this.to = 1;

    const step = () => {
      this.t += TICK_MS;
      this.players.forEach((p, i) => {
        p.x += p.vx;
        p.y += p.vy;
        if (p.x < PAD || p.x > W - PAD) p.vx *= -1;
        if (p.y < PAD || p.y > H - PAD) p.vy *= -1;
        p.x = clamp(p.x, PAD, W - PAD);
        p.y = clamp(p.y, PAD, H - PAD);
        // A small nudge each tick, so the paths do not settle into billiards.
        if (this.t % 800 < TICK_MS) {
          p.vx += (noise(this.t + i * 71) - 0.5) * 1.1;
          p.vy += (noise(this.t + i * 131) - 0.5) * 1.1;
          p.vx = clamp(p.vx, -3, 3);
          p.vy = clamp(p.vy, -3, 3);
        }
      });

      if (this.t - this.passStart >= PASS_MS) this.throwBall();
      if (this.t >= DURATION_MS) this.finish();
      this.render();
    };

    this.buildControls();

    if (prefersReducedMotion()) {
      // No animation: the task cannot be run, so hand over the count and go
      // straight to the question rather than pretending otherwise.
      this.silent = true;
      while (this.t < DURATION_MS) {
        this.t += TICK_MS;
        if (this.t - this.passStart >= PASS_MS) this.throwBall();
      }
      this.finish();
      this.render();
      return;
    }

    this.timer = this.every(TICK_MS, step);
    this.render();
  }

  /** Hand the ball on. Mostly within the team, sometimes across — without
   *  that the ball would stay with one team all clip and "count the white
   *  passes" would just mean "count the passes". */
  private throwBall(): void {
    const holder = this.players[this.to];
    const team = holder?.light ?? true;
    const across = noise(this.t * 7 + 29) < 0.3;
    const wanted = across ? !team : team;

    const options = this.players
      .map((p, i) => ({ p, i }))
      .filter(({ p, i }) => p.light === wanted && i !== this.to);
    const pick = options[Math.floor(noise(this.t * 3 + 11) * options.length) % options.length];

    this.from = this.to;
    this.to = pick.i;
    this.passStart = this.t;
    // A pass belongs to the team that threw it.
    if (team) this.passes += 1;
  }

  private finish(): void {
    if (this.timer) this.cancelInterval(this.timer);
    this.timer = 0;
    this.phase = 'counting';
    this.buildControls();
    this.delay(0, () => this.q<HTMLInputElement>('[data-sim-count]')?.focus());
  }

  private submitCount(): void {
    if (this.phase !== 'counting') return;
    const raw = this.q<HTMLInputElement>('[data-sim-count]')?.value ?? '';
    const n = Number.parseInt(raw, 10);
    if (!Number.isFinite(n)) return;
    this.guess = n;
    this.phase = 'asked';
    this.buildControls();
    this.render();
    this.emit('counted', { guess: n, actual: this.passes });
  }

  private answerSaw(yes: boolean): void {
    this.sawIt = yes;
    this.phase = 'done';
    // The trial is now spent: the insight beat unlocks and stays unlocked.
    this.revealed = true;
    this.buildControls();
    this.render();
    this.emit('answered', { sawIt: yes, viewings: this.viewings });
  }

  private reset(): void {
    if (this.timer) this.cancelInterval(this.timer);
    this.timer = 0;
    this.phase = 'idle';
    this.t = 0;
    this.passes = 0;
    this.guess = null;
    this.sawIt = null;
    this.buildControls();
    this.render();
    this.emit('reset');
  }

  /* ── the action bar, per mode and phase ── */

  private buildControls(): void {
    const bar = this.q('[data-sim-controls]');
    if (!bar) return;
    bar.innerHTML = '';

    // The insight beat runs itself — no controls.
    if (this.mode === 'insight') {
      bar.hidden = true;
      return;
    }
    bar.hidden = false;

    if (this.phase === 'idle') {
      const first = this.viewings === 0;
      this.addBtn(
        bar,
        first ? 'Start the clip' : 'Watch again — ringed',
        first ? 'sim-btn-primary' : 'sim-btn-outline',
        'data-sim-start',
      );
      if (this.revealed) this.addNav(bar);
      return;
    }

    if (this.phase === 'playing') {
      this.addBtn(bar, 'Counting…', 'sim-btn-primary', 'data-sim-start', true);
      return;
    }

    if (this.phase === 'counting' || this.phase === 'asked') {
      this.addBtn(
        bar,
        this.phase === 'counting' ? 'Enter your count above' : 'Answer the question above',
        'sim-btn-primary',
        'data-sim-start',
        true,
      );
      return;
    }

    // done
    this.addBtn(bar, 'Watch again — ringed', 'sim-btn-outline', 'data-sim-start');
    this.addBtn(bar, 'Reset', 'sim-btn-quiet', 'data-sim-reset');
    this.addNav(bar);
  }

  private addBtn(
    bar: HTMLElement,
    label: string,
    cls: string,
    hook: 'data-sim-start' | 'data-sim-reset',
    disabled = false,
  ): void {
    const b = document.createElement('button');
    b.type = 'button';
    b.className = `sim-btn ${cls}`;
    b.textContent = label;
    b.setAttribute(hook, '');
    if (disabled) b.disabled = true;
    else b.addEventListener('click', () => (hook === 'data-sim-start' ? this.start() : this.reset()));
    bar.appendChild(b);
  }

  /** A quiet pointer to the insight beat, once it is unlocked. */
  private addNav(bar: HTMLElement): void {
    const b = document.createElement('button');
    b.type = 'button';
    b.className = 'sim-btn sim-btn-quiet gor-nav';
    b.textContent = 'Why half miss it →';
    b.addEventListener('click', () => this.setMode('insight'));
    bar.appendChild(b);
  }

  /* ── view ── */

  private gorillaAt(): number | null {
    const f = this.t / DURATION_MS;
    if (f < GORILLA_FROM || f > GORILLA_TO) return null;
    return (f - GORILLA_FROM) / (GORILLA_TO - GORILLA_FROM);
  }

  protected render(): void {
    // tabs
    this.setAttribute('data-mode', this.mode);
    this.pressed('[data-sim-mode]', 'simMode', this.mode);
    this.gateInsightTab();
    this.show('[data-sim-mode-panel="trial"]', this.mode === 'trial');
    this.show('[data-sim-mode-panel="insight"]', this.mode === 'insight');

    // status word reflects the live trial regardless of which tab is open
    const playing = this.phase === 'playing';
    this.text(
      '[data-sim-status]',
      this.mode === 'insight'
        ? 'the insight'
        : playing
          ? `${Math.max(0, Math.ceil((DURATION_MS - this.t) / 1000))}s`
          : this.phase === 'idle'
            ? this.viewings > 0
              ? 'spent'
              : 'ready'
            : this.phase === 'done'
              ? 'done'
              : 'counting',
    );

    if (this.mode === 'insight') return;

    this.html('[data-sim-court]', this.courtSvg());
    this.q('[data-sim-court]')?.setAttribute('aria-label', this.stageLabel());
    this.show('[data-sim-count-row]', this.phase === 'counting');
    this.show('[data-sim-saw-row]', this.phase === 'asked');
    this.show('[data-sim-reveal]', this.phase === 'done');

    this.text('[data-sim-lead]', this.lead());
    this.text('[data-sim-actual]', this.guess === null ? '' : this.countLine());
    this.text('[data-sim-reveal]', this.phase === 'done' ? this.reveal() : '');
  }

  /** Lock the insight tab until the trial is spent. */
  private gateInsightTab(): void {
    const tab = this.q<HTMLButtonElement>('[data-sim-mode="insight"]');
    if (!tab) return;
    tab.disabled = !this.revealed;
    tab.setAttribute('aria-disabled', String(!this.revealed));
    tab.textContent = this.revealed ? 'The insight' : 'The insight \u{1F512}';
    tab.title = this.revealed ? 'Why half miss it' : 'Do the trial first — one naive viewing';
  }

  private courtSvg(): string {
    if (this.phase === 'idle')
      return (
        '<p class="gor-brief">Three players in white pass a ball between themselves, three in dark do the same. ' +
        '<b>Count the passes made by the white team.</b> It runs for sixteen seconds and you get one go at it.</p>'
      );

    const players = this.players
      .map(
        p =>
          `<circle class="gor-player ${p.light ? 'is-light' : 'is-dark'}" cx="${p.x.toFixed(1)}" cy="${p.y.toFixed(
            1,
          )}" r="11"/>`,
      )
      .join('');

    // The ball is in the air between the last player and the next one.
    const a = this.players[this.from];
    const b = this.players[this.to];
    const k = clamp((this.t - this.passStart) / PASS_MS, 0, 1);
    const ball =
      a && b
        ? `<circle class="gor-ball" cx="${(a.x + (b.x - a.x) * k).toFixed(1)}" cy="${(
            a.y +
            (b.y - a.y) * k -
            Math.sin(k * Math.PI) * 16
          ).toFixed(1)}" r="5"/>`
        : '';

    const g = this.gorillaAt();
    const gorilla =
      g === null
        ? ''
        : (() => {
            const gx = -30 + g * (W + 60);
            const gy = H / 2 + Math.sin(g * Math.PI * 3) * 8;
            const ring = this.marked
              ? `<ellipse class="gor-ring" cx="${gx.toFixed(1)}" cy="${gy.toFixed(1)}" rx="22" ry="30"/>`
              : '';
            return (
              ring +
              `<g class="gor-ape" transform="translate(${gx.toFixed(1)} ${gy.toFixed(1)}) scale(0.62)">` +
              '<ellipse cx="0" cy="4" rx="17" ry="24"/>' +
              '<circle cx="0" cy="-24" r="11"/>' +
              '<ellipse cx="-20" cy="2" rx="6" ry="18"/>' +
              '<ellipse cx="20" cy="2" rx="6" ry="18"/>' +
              '<ellipse cx="-8" cy="30" rx="6" ry="12"/>' +
              '<ellipse cx="8" cy="30" rx="6" ry="12"/>' +
              '</g>'
            );
          })();

    return (
      `<svg class="gor-svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="${this.stageLabel()}">` +
      `<rect class="gor-floor" x="0" y="0" width="${W}" height="${H}"/>` +
      gorilla +
      players +
      ball +
      `</svg>`
    );
  }

  private stageLabel(): string {
    if (this.phase === 'idle')
      return this.viewings > 0
        ? 'The court, at rest. You have already had your one naive viewing.'
        : 'A court, ready. Three players in white and three in dark will pass a ball; count the passes made by the white team.';
    if (this.phase === 'playing')
      return `Six players moving and passing. ${Math.max(0, Math.ceil((DURATION_MS - this.t) / 1000))} seconds left. Count the white team's passes.`;
    return 'The clip has finished. The court is at rest.';
  }

  /* ── captions and verdicts, matched to the state ── */

  private lead(): string {
    if (this.phase === 'idle')
      return this.viewings > 0
        ? 'That was your one viewing. You can run it again, but you cannot be naive twice — which is exactly why the original needed hundreds of people who had each seen it once.'
        : 'One viewing, and the counting task is real. When you are ready, start the clip and count the white team’s passes — nothing else is being asked of you.';
    if (this.phase === 'playing')
      return 'Keep counting the passes made by the white team. Stay with the task — that is the whole point.';
    if (this.phase === 'counting')
      return 'The clip is over. Before anything else, put in the number of white-team passes you counted.';
    if (this.phase === 'asked')
      return 'One more question, now that your count is in — did anything besides the players and the ball cross the frame?';
    // done
    if (this.silent)
      return 'With motion off the clip could not play, so the count was handed to you — but the finding still stands, and the insight beat is now open.';
    return this.sawIt === false
      ? 'You were counting, and something walked straight through the middle of it unseen. The insight beat is now open — it explains why.'
      : 'You caught it — about half of people do. The other half are the interesting ones. The insight beat is now open.';
  }

  private countLine(): string {
    const off = Math.abs((this.guess ?? 0) - this.passes);
    if (off === 0) return `${this.passes} passes, and you said ${this.guess}. Exactly right.`;
    if (off <= 2)
      return `${this.passes} passes, and you said ${this.guess}. Close enough that you were clearly doing the task.`;
    return `${this.passes} passes, and you said ${this.guess}.`;
  }

  /** The reveal — what actually walked through. Only ever shown once the count
   *  is in and the question answered, never before. */
  private reveal(): string {
    if (this.silent)
      return 'A person in a gorilla suit was scripted to walk into the middle of the frame, stop, beat their chest, and walk out — eight seconds in, in plain view, for over three seconds. With animation off it did not play, so there was nothing to miss here. On a moving clip, roughly half of people miss it entirely.';

    if (this.viewings > 1)
      return 'Second viewing, and the gorilla was ringed — impossible to miss now. That is precisely why the study needed hundreds of people: one subject is worth exactly one trial, and after that they can only ever be someone who already knows.';

    if (this.sawIt === false)
      return 'A person in a gorilla suit walked into the middle of the frame, stopped, beat their chest, and walked out — eight seconds in, in plain view, for over three seconds. Roughly half of people miss it, and they are not being careless: they are doing exactly what they were asked. Watch it again and it is impossible to miss, which is the part that is hard to accept.';

    return 'You saw it — about half of people do. The reason it splits is not effort or eyesight. It is that attention has to be spent on something, and yours was spent on the passes.';
  }
}

defineSim('gorilla-sim', GorillaSim);
