/**
 * <gorilla-sim> — count the passes.
 *
 * The design is spent after one viewing per subject, which is the whole reason
 * the original needed a large sample: you cannot un-know it. So the panel does
 * the same thing — it gives the reader one honest run at the task, asks for
 * the count first and only then asks the other question, and afterwards says
 * plainly that every later viewing is a different experiment.
 *
 * The counting task is real. Passes are generated by the ball actually being
 * thrown between players and the tally is whatever happened, so a reader who
 * concentrates gets it about right, which is what makes the miss worth
 * anything.
 */

import { SimElement, clamp, defineSim, noise, prefersReducedMotion } from './base';

type Phase = 'idle' | 'playing' | 'counting' | 'asked' | 'done';

interface Player {
  x: number;
  y: number;
  vx: number;
  vy: number;
  light: boolean;
}

const W = 320;
const H = 200;
const PAD = 22;
const DURATION_MS = 16000;
const TICK_MS = 40;
const PASS_MS = 700;
/** When the gorilla walks through, as a fraction of the whole clip. */
const GORILLA_FROM = 0.5;
const GORILLA_TO = 0.72;

class GorillaSim extends SimElement {
  private phase: Phase = 'idle';
  private t = 0;
  private timer = 0;
  private players: Player[] = [];
  private from = 0;
  private to = 1;
  private passStart = 0;
  private passes = 0;
  private guess: number | null = null;
  private sawIt: boolean | null = null;
  private viewings = 0;
  /** After the first run, the gorilla is drawn ringed. */
  private marked = false;

  protected setup(): void {
    this.onClick('[data-sim-start]', () => this.start());
    this.onClick('[data-sim-submit]', () => this.submitCount());
    this.onClick('[data-sim-saw]', el => this.answerSaw(el.dataset.simSaw === 'yes'));
    this.onClick('[data-sim-reset]', () => this.reset());
    this.on('[data-sim-count]', 'keydown', (_el, event) => {
      if ((event as KeyboardEvent).key === 'Enter') {
        event.preventDefault();
        this.submitCount();
      }
    });
  }

  protected teardown(): void {
    if (this.timer) this.cancelInterval(this.timer);
  }

  /* ── the clip ── */

  private start(): void {
    this.viewings += 1;
    this.marked = this.viewings > 1;
    this.phase = 'playing';
    this.t = 0;
    this.passes = 0;
    this.guess = null;
    this.sawIt = null;
    this.passStart = 0;

    this.players = Array.from({ length: 6 }, (_, i) => ({
      x: PAD + noise(i * 37 + this.viewings * 13) * (W - 2 * PAD),
      y: PAD + noise(i * 91 + this.viewings * 7) * (H - 2 * PAD),
      vx: (noise(i * 17 + 3) - 0.5) * 2.6,
      vy: (noise(i * 53 + 5) - 0.5) * 2.6,
      light: i < 3,
    }));
    this.from = 0;
    this.to = 1;

    const step = () => {
      this.t += TICK_MS;
      this.players.forEach((p, i) => {
        p.x += p.vx;
        p.y += p.vy;
        if (p.x < PAD || p.x > W - PAD) p.vx *= -1;
        if (p.y < PAD || p.y > H - PAD) p.vy *= -1;
        p.x = clamp(p.x, PAD, W - PAD);
        p.y = clamp(p.y, PAD, H - PAD);
        // A small nudge each tick, so the paths do not settle into billiards.
        if (this.t % 800 < TICK_MS) {
          p.vx += (noise(this.t + i * 71) - 0.5) * 1.1;
          p.vy += (noise(this.t + i * 131) - 0.5) * 1.1;
          p.vx = clamp(p.vx, -3, 3);
          p.vy = clamp(p.vy, -3, 3);
        }
      });

      if (this.t - this.passStart >= PASS_MS) this.throwBall();
      if (this.t >= DURATION_MS) this.finish();
      this.render();
    };

    if (prefersReducedMotion()) {
      // No animation: the task cannot be run, so hand over the count and go
      // straight to the question rather than pretending otherwise.
      while (this.t < DURATION_MS) {
        this.t += TICK_MS;
        if (this.t - this.passStart >= PASS_MS) this.throwBall();
      }
      this.finish();
      this.render();
      return;
    }

    this.timer = this.every(TICK_MS, step);
    this.render();
  }

  /** Hand the ball on. Mostly within the team, sometimes across — without
   *  that the ball would stay with one team all clip and "count the white
   *  passes" would just mean "count the passes". */
  private throwBall(): void {
    const holder = this.players[this.to];
    const team = holder?.light ?? true;
    const across = noise(this.t * 7 + 29) < 0.3;
    const wanted = across ? !team : team;

    const options = this.players
      .map((p, i) => ({ p, i }))
      .filter(({ p, i }) => p.light === wanted && i !== this.to);
    const pick = options[Math.floor(noise(this.t * 3 + 11) * options.length) % options.length];

    this.from = this.to;
    this.to = pick.i;
    this.passStart = this.t;
    // A pass belongs to the team that threw it.
    if (team) this.passes += 1;
  }

  private finish(): void {
    if (this.timer) this.cancelInterval(this.timer);
    this.timer = 0;
    this.phase = 'counting';
    this.delay(0, () => this.q<HTMLInputElement>('[data-sim-count]')?.focus());
  }

  private submitCount(): void {
    if (this.phase !== 'counting') return;
    const raw = this.q<HTMLInputElement>('[data-sim-count]')?.value ?? '';
    const n = Number.parseInt(raw, 10);
    if (!Number.isFinite(n)) return;
    this.guess = n;
    this.phase = 'asked';
    this.render();
    this.emit('counted', { guess: n, actual: this.passes });
  }

  private answerSaw(yes: boolean): void {
    this.sawIt = yes;
    this.phase = 'done';
    this.render();
    this.emit('answered', { sawIt: yes, viewings: this.viewings });
  }

  private reset(): void {
    if (this.timer) this.cancelInterval(this.timer);
    this.timer = 0;
    this.phase = 'idle';
    this.t = 0;
    this.passes = 0;
    this.guess = null;
    this.sawIt = null;
    this.render();
    this.emit('reset');
  }

  /* ── view ── */

  private gorillaAt(): number | null {
    const f = this.t / DURATION_MS;
    if (f < GORILLA_FROM || f > GORILLA_TO) return null;
    return (f - GORILLA_FROM) / (GORILLA_TO - GORILLA_FROM);
  }

  protected render(): void {
    const playing = this.phase === 'playing';

    this.text(
      '[data-sim-status]',
      playing ? `${Math.max(0, Math.ceil((DURATION_MS - this.t) / 1000))}s` : this.phase === 'idle' ? 'ready' : 'done',
    );

    this.html('[data-sim-court]', this.courtSvg());
    this.show('[data-sim-count-row]', this.phase === 'counting');
    this.show('[data-sim-saw-row]', this.phase === 'asked');
    this.show('[data-sim-result]', this.phase === 'done');
    this.disable('[data-sim-start]', playing);

    this.text('[data-sim-task]', this.task());
    this.text('[data-sim-actual]', this.guess === null ? '' : this.countLine());
    this.text('[data-sim-verdict]', this.verdict());
  }

  private courtSvg(): string {
    if (this.phase === 'idle')
      return (
        '<p class="gor-brief">Three players in white pass a ball between themselves, three in dark do the same. ' +
        '<b>Count the passes made by the white team.</b> It runs for sixteen seconds and you get one go at it.</p>'
      );

    const players = this.players
      .map(
        p =>
          `<circle class="gor-player ${p.light ? 'is-light' : 'is-dark'}" cx="${p.x.toFixed(1)}" cy="${p.y.toFixed(
            1,
          )}" r="11"/>`,
      )
      .join('');

    // The ball is in the air between the last player and the next one.
    const a = this.players[this.from];
    const b = this.players[this.to];
    const k = clamp((this.t - this.passStart) / PASS_MS, 0, 1);
    const ball =
      a && b
        ? `<circle class="gor-ball" cx="${(a.x + (b.x - a.x) * k).toFixed(1)}" cy="${(
            a.y +
            (b.y - a.y) * k -
            Math.sin(k * Math.PI) * 16
          ).toFixed(1)}" r="5"/>`
        : '';

    const g = this.gorillaAt();
    const gorilla =
      g === null
        ? ''
        : (() => {
            const gx = -30 + g * (W + 60);
            const gy = H / 2 + Math.sin(g * Math.PI * 3) * 8;
            const ring = this.marked
              ? `<ellipse class="gor-ring" cx="${gx.toFixed(1)}" cy="${gy.toFixed(1)}" rx="22" ry="30"/>`
              : '';
            return (
              ring +
              `<g class="gor-ape" transform="translate(${gx.toFixed(1)} ${gy.toFixed(1)}) scale(0.62)">` +
              '<ellipse cx="0" cy="4" rx="17" ry="24"/>' +
              '<circle cx="0" cy="-24" r="11"/>' +
              '<ellipse cx="-20" cy="2" rx="6" ry="18"/>' +
              '<ellipse cx="20" cy="2" rx="6" ry="18"/>' +
              '<ellipse cx="-8" cy="30" rx="6" ry="12"/>' +
              '<ellipse cx="8" cy="30" rx="6" ry="12"/>' +
              '</g>'
            );
          })();

    return (
      `<svg class="gor-svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="Six players moving and passing a ball. Count the passes made by the white team.">` +
      `<rect class="gor-floor" x="0" y="0" width="${W}" height="${H}"/>` +
      gorilla +
      players +
      ball +
      `</svg>`
    );
  }

  private task(): string {
    if (this.phase === 'idle') return 'One viewing. The count is what you are being asked for.';
    if (this.phase === 'playing') return 'Count the passes made by the white team.';
    if (this.phase === 'counting') return 'How many passes did the white team make?';
    if (this.phase === 'asked') return 'One more question.';
    return 'That is the experiment. There is nothing else to do with it.';
  }

  private countLine(): string {
    const off = Math.abs((this.guess ?? 0) - this.passes);
    if (off === 0) return `${this.passes} passes, and you said ${this.guess}. Exactly right.`;
    if (off <= 2) return `${this.passes} passes, and you said ${this.guess}. Close enough that you were clearly doing the task.`;
    return `${this.passes} passes, and you said ${this.guess}.`;
  }

  private verdict(): string {
    if (this.phase !== 'done') {
      if (this.phase === 'idle' && this.viewings > 0)
        return 'You can run it again, but you will not be a naive subject twice. That is the constraint the original was built around.';
      return 'The counting task is real — the passes are actually thrown, and the tally is whatever happened.';
    }

    if (this.viewings > 1)
      return 'Second viewing, and the gorilla is ringed. This is why the study needed hundreds of people: one subject is worth exactly one trial, and after that they can only ever be someone who knows.';

    if (this.sawIt === false)
      return 'A person in a gorilla suit walked into the middle of the frame, stopped, and walked out — eight seconds in, in plain view, for three and a half seconds. Roughly half of people miss it, and they are not being careless: they are doing exactly what they were asked to do. Watch it again and it is impossible to miss, which is the part that is hard to accept.';

    return 'You saw it — about half of people do. The interesting half is the other one, and the reason it splits is not effort or eyesight. It is that attention has to be spent on something, and it was spent on the passes.';
  }
}

defineSim('gorilla-sim', GorillaSim);
